-- -----------------------------------------------------
-- Table parking_slot_type
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_slot_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL ,
    PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table pricing_policy
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS pricing_policy (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    formula BLOB NOT NULL,
    created DATETIME NOT NULL,
    PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table parking
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS parking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(45) NOT NULL,
    pricing_policy_id INT  NOT NULL,
    created DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT parking_pricing_policy_id
    FOREIGN KEY (pricing_policy_id)
    REFERENCES pricing_policy (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table car
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS car (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_plate VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL ,
    PRIMARY KEY (id),
    UNIQUE (registration_plate));


-- -----------------------------------------------------
-- Table parking_slot
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS parking_slot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parking_id INT  NOT NULL,
    parking_slot_type_id INT  NOT NULL,
    car_id INT NULL,
    is_free BOOLEAN NOT NULL,
    created DATETIME NOT NULL ,
    PRIMARY KEY (id),
    CONSTRAINT parking_slot_parking_slot_type_id
    FOREIGN KEY (parking_slot_type_id)
    REFERENCES parking_slot_type (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT parking_slot_parking_id
    FOREIGN KEY (parking_id)
    REFERENCES parking (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT parking_slot_car_id
    FOREIGN KEY (car_id)
    REFERENCES car (id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table visit_log
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS visit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parking_id INT  NOT NULL,
    car_id INT  NOT NULL,
    entry_time DATETIME NULL,
    exit_time DATETIME NULL,
    PRIMARY KEY (id),
    CONSTRAINT visit_log_car_id
    FOREIGN KEY (car_id)
    REFERENCES car (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT visit_log_parking_id
    FOREIGN KEY (parking_id)
    REFERENCES parking (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table bill
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS bill (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parking_slot_id INT  NOT NULL,
    visit_log_id INT  NOT NULL,
    amount DOUBLE NOT NULL,
    created DATETIME NOT NULL ,
    PRIMARY KEY (id),
    CONSTRAINT bill_parking_slot_id
    FOREIGN KEY (parking_slot_id)
    REFERENCES parking_slot (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT bill_visit_log_id
    FOREIGN KEY (visit_log_id)
    REFERENCES visit_log (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
